# Railway deployment configuration
# https://railway.app/

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${{Postgres.DATABASE_URL}}
      - JWT_SECRET=${{JWT_SECRET}}
      - NODE_ENV=production
    healthcheck:
      path: /
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=qa_user
      - POSTGRES_PASSWORD=${{POSTGRES_PASSWORD}}
      - POSTGRES_DB=qa_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
